### ISSUE TITLE
If hash is found it wont submit

### ISSUE THREAD

**Issue by abaddon30** [iceland2k14/solominer#12]
sock is not defined here :)

 if hash < target :
            # init a connection to ckpool 
            logg('[*] Block {} solved.'.format(work_on+1))
            logg('[*] Block hash: {}'.format(hash))
            logg('[*] Blockheader: {}'.format(blockheader))            
            payload = bytes('{"params": ["'+address+'", "'+ctx.job_id+'", "'+ctx.extranonce2 \
                +'", "'+ctx.ntime+'", "'+nonce+'"], "id": 1, "method": "mining.submit"}\n', 'utf-8')
            logg('[*] Payload: {}'.format(payload))
            sock.sendall(payload)
            ret = sock.recv(1024)

**Comment by thearthouse** [comment]
ctx.extranonce2 also not defined

**Comment by iceland2k14** [comment]
Updated in #13
